### ISSUE TITLE
Loading tickets

### ISSUE THREAD

**Issue by issebilen** [gianlucadetommaso/volatile#2]
![image](https://user-images.githubusercontent.com/42683217/104137830-ff1e1880-539f-11eb-8ebf-fa510aa5babc.png)

I have tried this last week and it worked fine. But now it doesn't load the tickets. I tried with less tickets, around 300 and it only loaded 5 tickets. Those tickets are in this run, but now it wont load any tickets. This is the swedish stocks I am trying to load: 

PFE.ST AZN.ST ATCO-A.ST ABB.ST ATCO-B.ST INVE-B.ST INVE-A.ST VOLV-B.ST VOLV-A.ST ERIC-A.ST ERIC-B.ST HM-B.ST NDA-SE.ST HEXA-B.ST SAND.ST ASSA-B.ST EQT.ST SEB-C.ST SEB-A.ST ESSITY-B.ST ESSITY-A.ST NOKIA-SEK.ST EPI-B.ST EPI-A.ST SHB-B.ST EVO.ST SHB-A.ST SWED-A.ST TELIA.ST NIBE-B.ST LATO-B.ST STE-A.ST STE-R.ST INDU-A.ST INDU-C.ST KINV-A.ST KINV-B.ST 8TRA.ST LUND-B.ST SWMA.ST SCA-B.ST SCA-A.ST SKF-B.ST SKF-A.ST ALFA.ST SKA-B.ST ICA.ST EMBRAC-B.ST BOL.ST SINCH.ST BALD-B.ST TEL2-B.ST TEL2-A.ST LIFCO-B.ST ALIV-SDB.ST HOLM-B.ST HOLM-A.ST INDT.ST LUNE.ST HUSQ-A.ST HUSQ-B.ST ELUX-A.ST CAST.ST SAGA-A.ST SAGA-B.ST ELUX-B.ST SAGA-D.ST SWEC-B.ST SWEC-A.ST VOLO-PREF.ST GETI-B.ST LUMI.ST SSAB-B.ST SSAB-A.ST TREL-B.ST SECU-B.ST SOBI.ST BEIJ-B.ST SBB-B.ST SBB-D.ST AAK.ST EKTA-B.ST FABG.ST WALL-B.ST AXFO.ST SF.ST AZA.ST SAVE.ST DOM.ST SAGA-PREF.ST SAAB-B.ST TIGO-SDB.ST THULE.ST TIETOS.ST NENT-A.ST HPOL-B.ST NENT-B.ST BILL.ST ADDT-B.ST SECT-B.ST AF-B.ST WIHL.ST HUFV-A.ST INTRUM.ST PDX.ST PEAB-B.ST PNDX-B.ST MYCR.ST MCOV-B.ST VITR.ST RECI-B.ST BRAV.ST NOLA-B.ST ATRLJ-B.ST BURE.ST AM1S.ST VNE-SDB.ST JM.ST KLED.ST HEBA-B.ST KIND-SDB.ST BHG.ST ARJO-B.ST FPAR-A.ST FPAR-D.ST PCELL.ST LOOMIS.ST NCC-B.ST STORY-B.ST NCC-A.ST LUG.ST ALIF-B.ST NYF.ST FPAR-PREF.ST MTRS.ST CATE.ST KLOV-B.ST KLOV-A.ST MIPS.ST EPRO-B.ST KLOV-PREF.ST FOI-B.ST SYSR.ST CORE-B.ST LIAB.ST HMS.ST INSTAL.ST PLAZ-B.ST RATO-A.ST RATO-B.ST KARO.ST SAS.ST CLNK-B.ST BOOZT.ST TROAX.ST KAMBI.ST ONCO.ST HNSA.ST NOBI.ST CRED-A.ST SBB-PREF.ST VNV.ST VIT-B.ST GRNG.ST IVSO.ST BETS-B.ST BIOG-B.ST MTG-A.ST MTG-B.ST CAMX.ST DIOS.ST BILI-A.ST ARION-SDB.ST EG7.ST KFAST-B.ST ANOD-B.ST BIOT.ST VOLO.ST RESURS.ST XVIVO.ST ACAD.ST ALM-PREF.ST ALM.ST BONAV-A.ST BONAV-B.ST BIOA-B.ST VBG-B.ST SKIS-B.ST SEDANA.ST SDIP-PREF.ST SDIP-B.ST CORE-PREF.ST CORE-A.ST CEVI.ST BEIA-B.ST NYTTO.ST OEM-B.ST COIC.ST BUFAB.ST ALIG.ST BETCO.ST CLA-B.ST COOR.ST INWI.ST ATT.ST CALTX.ST MMGR-B.ST GPG-PREF.ST CIBUS.ST SECARE.ST NP3.ST KNOW.ST GARO.ST RENEW.ST AMBEA.ST NOBINA.ST SHOT.ST NMAN.ST DUST.ST KAR.ST CANTA.ST ORES.ST TOBII.ST HEIM-PREF.ST SVOL-A.ST EOLU-B.ST MSON-B.ST THUNDR.ST MSON-A.ST MEKO.ST TRIAN-B.ST LIME.ST LAGR-B.ST FAG.ST LYKO-A.ST DUNI.ST BONEX.ST COLL.ST AZELIO.ST NCAB.ST CLAS-B.ST FING-B.ST PROB.ST SVOL-B.ST QLINEA.ST JOMA.ST BACTI-B.ST ADAPT.ST AMAST.ST SCST.ST SIVE.ST ABSO.ST PRIC-B.ST ELAN-B.ST STEF-B.ST NP3-PREF.ST NANOFS.ST BTS-B.ST AQ.ST OFFHUS.ST FG.ST ENEA.ST XANO-B.ST NWG.ST G5EN.ST NEWA-B.ST K2A-B.ST ELTEL.ST SEYE.ST AEC.ST AOI.ST PEGRO-PREF.ST LEO.ST FOOT-B.ST MCAP.ST REJL-B.ST VEFL-SDB.ST MINEST.ST SUS.ST OVZON.ST HOFI.ST WBGR-B.ST BMAX.ST BUSER.ST HUM.ST XSPRAY.ST GPG.ST IPCO.ST ENZY.ST HTRO.ST RAY-B.ST TRAC-B.ST NLAB.ST EAST.ST IMMNOV.ST IVACC.ST BERG-B.ST NPAPER.ST ASPIRE.ST BRIN-B.ST PACT.ST HANDI.ST CLIME-B.ST ISOFOL.ST CAT-B.ST ZZ-B.ST FNM.ST READ.ST FMM-B.ST VICO.ST CAT-A.ST FNOVA-B.ST ENQ.ST MAG.ST DMYD-B.ST IRLAB-A.ST MNTC.ST HLDX.ST CCC.ST BALCO.ST BRE2.ST BIM.ST BESQ.ST M8G.ST BAYN.ST BINV.ST OASM.ST BULTEN.ST CTM.ST IAR-B.ST CTT.ST GHP.ST GENO.ST TFBANK.ST KOPY.ST GREEN.ST SOLT.ST CI-B.ST ANNE-B.ST SPEC.ST ITAB-B.ST NOTE.ST ACE.ST TETY.ST XBRANE.ST FPIP.ST ORX.ST CRAD-B.ST CDON.ST AMAST-PREF.ST FOOT-PREF.ST SENS.ST FASTAT.ST BIOVIC-B.ST BIOGAS.ST JOSE.ST SES.ST GAPW-B.ST KABE-B.ST SEZI.ST FIL.ST ARISE.ST MAHA-A.ST SANION.ST SEMC.ST EWRK.ST STRLNG.ST SRNKE-B.ST LUC.ST TRAIN-B.ST SFAST.ST IMPC.ST IBT-B.ST RROS.ST 3KR.ST AJA-B.ST SOF-B.ST BOUL.ST BELE.ST DORO.ST NHCBHFFS.ST DURC-B.ST FLEXM.ST ATA-SDB.ST SCOUT.ST BRG-B.ST GIGSEK.ST TORSAB.ST ATVEXA-B.ST ORGC.ST PLED.ST ETX.ST UPSALE.ST FERRO.ST ELOS-B.ST INZILE.ST SINT.ST ODD.ST IRIS.ST ITECH.ST JETPAK.ST SVIK.ST ARP.ST CNCJO-B.ST GREAT.ST TEQ.ST AXIC-A.ST ALLG-B.ST MAGI.ST KAN.ST STAR-A.ST MSAB-B.ST EXS.ST STAR-B.ST BYGGP.ST POLYG.ST SVED-B.ST MAXF.ST INTEG-B.ST IMMU.ST MANG.ST SPEONE.ST GOMX.ST NEXAM.ST PROF-B.ST NELLY.ST QLIRO.ST QAIR.ST PREV-B.ST KAPIAB.ST AVEN.ST 24STOR.ST ATRE.ST NETI-B.ST RO.ST HOVD.ST ZWIPE.ST MIDS.ST SOLNA.ST AWRD.ST SNM.ST RAIL.ST EPIS-B.ST ASAI.ST IRRAS.ST DIST.ST BRIG.ST PENG-B.ST PRCO-B.ST URBIT.ST AUR.ST OPTI.ST SKMO.ST NTEK-B.ST NAXS.ST GENI.ST SSM.ST VSSAB-B.ST COPP-B.ST ACCON.ST STRAX.ST ATORX.ST INISS-B.ST BORG.ST BEGR.ST NXTCL.ST EOS.ST HANZA.ST CBTT-B.ST NIL-B.ST CAG.ST DIGN.ST LOHILO.ST ZIGN.ST STWK.ST ALCA.ST MEAB-B.ST NXTMS.ST LIDDS.ST STIL.ST MIDW-A.ST MIDW-B.ST CE.ST CLEM.ST TRANS.ST INFREA.ST MAGLE.ST PIEZO.ST INDEX.ST PREC.ST HRNTS.ST CCOR-B.ST RLS.ST RAKE.ST CFISH.ST PAX.ST ICO.ST ACRI.ST LITI.ST SDS.ST ENDO.ST QUART.ST KDEV.ST ZETA.ST LCLEAN.ST GHUS-B.ST LOG.ST SALT-B.ST AAC.ST B3.ST LIPI.ST DDM.ST DEDI.ST NNH.ST FIRE.ST LAMM-B.ST SLITE.ST ALZCUR.ST TAGM-B.ST OSSD.ST MOBA.ST AKEL-D.ST ACROUD.ST CLAV.ST BONAS.ST ECC-B.ST REALFI.ST AGES-B.ST TSEC.ST OXE.ST EXPRS2.ST NANEXA.ST LEMSE.ST STW.ST NEPA.ST BONES.ST KLAR.ST SIGN-B.ST SAXG.ST EDGE.ST FEEL.ST ACTI.ST SPEQT.ST POOL-B.ST BOTX.ST TRENT.ST FREJA.ST SENZA.ST DRIL.ST BIOS.ST ARCOMA.ST BIOWKS.ST ADDV-B.ST ADDV-A.ST AEGIR.ST ELEC.ST GUARD.ST XMR.ST ACOU.ST SCIB.ST ZICC.ST CYXO.ST HAV-B.ST SJR-B.ST ZUTEC.ST FLUI.ST CLBIO.ST ISR.ST ABLI.ST SFTR.ST JDT.ST XINT.ST MYFC.ST AAA.ST ATIC.ST 2CUREX.ST NETM-B.ST OP-PREF.ST ORTI-A.ST ORTI-B.ST UNIBAP.ST TERRNT-B.ST ECOWVE.ST CLS-B.ST QLIFE.ST FLEXQ.ST WISE.ST K2A-PREF.ST QUART-PREF.ST LINKAB.ST MVIR-B.ST ERMA.ST VERT-B.ST FRISQ.ST HIFA-B.ST AROC.ST HELIO.ST TCT.ST SDOS.ST ACARIX.ST HOYLU.ST ALLR.ST MISE.ST DEVP-B.ST SPRINT.ST COMBI.ST DIVIO-B.ST SERT.ST ALELIO.ST RPLAN.ST MOB.ST OP.ST TALK.ST JLT.ST MACK-B.ST LOUDS.ST ANOT.ST SEAF.ST BUBL.ST INCOAX.ST GCOR.ST ADVE.ST ANNX.ST DOXA.ST TRAD.ST NGS.ST PROGEN.ST SBOK.ST IS.ST ADVBOX.ST FRAM-B.ST BINERO.ST ASAP.ST PCAT.ST S2M.ST PLUN.ST KONT.ST BONG.ST ALZ.ST RIZZO-B.ST VOLAB.ST GPX.ST MULQ.ST WAYS.ST ADDERA.ST MAV.ST CIRCHE.ST IZAFE-B.ST TRG.ST LEX.ST CAPAC.ST WPAY.ST PROMO.ST SAVOS.ST SECS.ST POLY.ST LXB.ST AYIMA-B.ST NIO.ST TOL.ST QUIA.ST NEWTON.ST ARCT.ST SIMRIS-B.ST VEVEN.ST TOURN.ST NITRO.ST CMOTEC-B.ST GABA.ST GGEO.ST ME.ST KEBNI-B.ST SECI.ST KAKEL.ST PHLOG-B.ST EMPIR-B.ST ENERS.ST SPIFF.ST KENH.ST NICO.ST RNBS.ST CHRO.ST ENRO.ST HDW-B.ST LIVI.ST IDOGEN.ST AERO.ST NBZ.ST EFFP.ST STABL.ST MOMENT.ST IVISYS.ST DIAH.ST AVT-B.ST AINO.ST TRIBO-B.ST INVAJO.ST TANGI.ST BOMILL.ST ZAPLOX.ST KOLL.ST HEMC.ST AXOLOT.ST UTG.ST LAUR.ST GPXMED.ST HEGR.ST MANTEX.ST NFGAB.ST ELN.ST FRILL-B.ST WESC.ST CONF.ST CUR.ST CLEMO.ST SONE.ST STUDBO.ST PAPI.ST DOME.ST NILS.ST NJOB.ST PCOM-B.ST CYB1.ST OBAB.ST

**Comment by gianlucadetommaso** [comment]
@issebilen looking into it. This is unfortunately something happening in **yfinance**, not really Volatile. It is most likely due to either the dots or the dashes in the symbol strings. I'll let you know if I find a way to get around the issue.

**Comment by gianlucadetommaso** [comment]
@issebilen fixed. The problem was rather that the data of those Swedish stocks come with lots of NaNs. I loosened some threshold and now it should work.
