### ISSUE TITLE
Do you have plan to provide a interact jupyter notebook to dive into the model construction ?

### ISSUE THREAD

**Issue by svjack** [gianlucadetommaso/volatile#3]
The tensorflow official website provide a example about multilevel modeling
https://www.tensorflow.org/probability/examples/Multilevel_Modeling_Primer
it interpret its components by visualize them separately.
I think you should also provide a correspondence about your model.
Let it to validate your model construction and change to adapt their own applications.
Even, if you have a guide about the feature selection and aggregate method 
in your model with visualize is more bravo.

**Comment by gianlucadetommaso** [comment]
Thank you for the pointer, @svjack. 

Visualizing the probabilistic graph underlying the model would definitely help both less and more experienced users. A specific tutorial about model construction would be a nice extra, however it is not high in my priority list; there are several other items I'm planning to address first.

**Comment by svjack** [comment]
> Thank you for the pointer, @svjack.
> 
> Visualizing the probabilistic graph underlying the model would definitely help both less and more experienced users. A specific tutorial about model construction would be a nice extra, however it is not high in my priority list; there are several other items I'm planning to address first.

As you describe different sector and industry trend in volatile.py and make it as static, and your tournament.py
describe different bots performance. May you provide a dynamic strategy change switch bot by your industry trend
prediction as conditions  ?

**Comment by svjack** [comment]
And i find Bayesian hierarchical model is advanced in interpretation with some confidence . Does this project 
will provide some optimization rather than only interpretation?

**Comment by gianlucadetommaso** [comment]
At the moment bots strategies are very simple, but more advanced ones are planned and in the making. 

Not sure what you mean by optimization vs interpretation here. Model parameters are optimized to estimates stock trends. The latter are used to provide a rate and a growth indicator, which I guess is what you call interpretation.

If by optimization you mean providing some sort of optimized bot strategies, the answer is yes, that will come.
