### ISSUE TITLE
Error with tensorflow 2.4 installation

### ISSUE THREAD

**Issue by bhralzz** [gianlucadetommaso/volatile#4]
dear Gianluca
I have been installed TensorFlow 2.4 downloading the file, then by
pip install tensorflow_cpu-2.4.0-cp36-cp36m-win_amd64.whl
 but I reached this error when running the code:

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.4; Detected an installation of version 2.3.0-dev20200603. Please upgrade TensorFlow to proceed.

found that the actual installed version of TensorFlow is 2.3, so the code is correct and the version of TensorFlow cause the error.

please provide a version of the code using a lower version of TensorFlow if possible!

I am waiting to hear your response.

thanks

**Comment by gianlucadetommaso** [comment]
Hi @bhralzz,
unfortunately model and inference are currently implemented in TensorFlow Probability, which seems to be stable only from version 2.4; see [here](https://github.com/tensorflow/probability/releases). Would it be a problem to just update TensorFlow?

Alternatively, I would encourage you to use Google Colab, as suggested in the installation section. TF is already installed and you will avoid these problems.

**Comment by bhralzz** [comment]
Thanks for your help!
