### ISSUE TITLE
Yahoo finance add headers 

### ISSUE THREAD

**Issue by karthikpappu** [gianlucadetommaso/volatile#7]
With recent update to yahoo finance, we need to update add a header when we query yahoo.

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by karthikpappu** [comment]
This should fix the issue

    headers = {
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    url = "{}/v8/finance/chart/{}".format(base_url, ticker)
    data = requests.get(url=url, params=params,headers=headers)

**Comment by gianlucadetommaso** [comment]
Have you tried to pull the last commit? It was meant to solve exactly that issue.

**Comment by karthikpappu** [comment]
I think, I might not have done that.
